[query]
category = "quant-ph"

[highlight]
keywords = ["error", "correction", "QEC", "superconducting"]
authors = ["Devoret", "Oliver", "Schuster", "Wallraff", "Lukin", "Gidney", "Siddiqi", "Girvin", "Schoelkopf"]
